//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.06 at 01:17:17 PM IST 
//


package com.ibm.csi.npm.dvreportmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MatricMediatorFormula complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MatricMediatorFormula">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ibm.com/csi/npm/dvreportermodel}TableMediatorFormula">
 *       &lt;sequence>
 *         &lt;element name="sourceDestination" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="threshold" type="{http://www.ibm.com/csi/npm/dvreportermodel}MatrixMediatorThreshold" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MatricMediatorFormula", propOrder = {
    "sourceDestination",
    "threshold"
})
public class MatricMediatorFormula
    extends TableMediatorFormula
{

    protected String sourceDestination;
    protected MatrixMediatorThreshold threshold;

    /**
     * Gets the value of the sourceDestination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceDestination() {
        return sourceDestination;
    }

    /**
     * Sets the value of the sourceDestination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceDestination(String value) {
        this.sourceDestination = value;
    }

    /**
     * Gets the value of the threshold property.
     * 
     * @return
     *     possible object is
     *     {@link MatrixMediatorThreshold }
     *     
     */
    public MatrixMediatorThreshold getThreshold() {
        return threshold;
    }

    /**
     * Sets the value of the threshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatrixMediatorThreshold }
     *     
     */
    public void setThreshold(MatrixMediatorThreshold value) {
        this.threshold = value;
    }

}
