//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.06 at 01:17:17 PM IST 
//


package com.ibm.csi.npm.dvreportmodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MatrixTableWidget complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MatrixTableWidget">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ibm.com/csi/npm/dvreportermodel}Widget">
 *       &lt;sequence>
 *         &lt;element name="drilldown" type="{http://www.ibm.com/csi/npm/dvreportermodel}MatrixDrilldown" minOccurs="0"/>
 *         &lt;element name="firstCellLabels" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rowColumnsLabels" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rotate" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="formulas" type="{http://www.ibm.com/csi/npm/dvreportermodel}TableFormulaWithoutTH" maxOccurs="unbounded"/>
 *         &lt;element name="cellFormat" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="displayLegend" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MatrixTableWidget", propOrder = {
    "drilldown",
    "firstCellLabels",
    "rowColumnsLabels",
    "rotate",
    "formulas",
    "cellFormat",
    "displayLegend"
})
public class MatrixTableWidget
    extends Widget
{

    protected MatrixDrilldown drilldown;
    protected String firstCellLabels;
    protected String rowColumnsLabels;
    protected Boolean rotate;
    @XmlElement(required = true)
    protected List<TableFormulaWithoutTH> formulas;
    protected String cellFormat;
    protected String displayLegend;

    /**
     * Gets the value of the drilldown property.
     * 
     * @return
     *     possible object is
     *     {@link MatrixDrilldown }
     *     
     */
    public MatrixDrilldown getDrilldown() {
        return drilldown;
    }

    /**
     * Sets the value of the drilldown property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatrixDrilldown }
     *     
     */
    public void setDrilldown(MatrixDrilldown value) {
        this.drilldown = value;
    }

    /**
     * Gets the value of the firstCellLabels property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstCellLabels() {
        return firstCellLabels;
    }

    /**
     * Sets the value of the firstCellLabels property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstCellLabels(String value) {
        this.firstCellLabels = value;
    }

    /**
     * Gets the value of the rowColumnsLabels property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRowColumnsLabels() {
        return rowColumnsLabels;
    }

    /**
     * Sets the value of the rowColumnsLabels property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRowColumnsLabels(String value) {
        this.rowColumnsLabels = value;
    }

    /**
     * Gets the value of the rotate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRotate() {
        return rotate;
    }

    /**
     * Sets the value of the rotate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRotate(Boolean value) {
        this.rotate = value;
    }

    /**
     * Gets the value of the formulas property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the formulas property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormulas().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TableFormulaWithoutTH }
     * 
     * 
     */
    public List<TableFormulaWithoutTH> getFormulas() {
        if (formulas == null) {
            formulas = new ArrayList<TableFormulaWithoutTH>();
        }
        return this.formulas;
    }

    /**
     * Gets the value of the cellFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCellFormat() {
        return cellFormat;
    }

    /**
     * Sets the value of the cellFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCellFormat(String value) {
        this.cellFormat = value;
    }

    /**
     * Gets the value of the displayLegend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayLegend() {
        return displayLegend;
    }

    /**
     * Sets the value of the displayLegend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayLegend(String value) {
        this.displayLegend = value;
    }

}
