//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.06 at 01:17:17 PM IST 
//


package com.ibm.csi.npm.dvreportmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RankVariationMediator complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RankVariationMediator">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ibm.com/csi/npm/dvreportermodel}Mediator">
 *       &lt;sequence>
 *         &lt;element name="metrics" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="numberOfResults" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="stats" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="topRank" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="valueOver" type="{http://www.ibm.com/csi/npm/dvreportermodel}Value"/>
 *         &lt;element name="valueUnder" type="{http://www.ibm.com/csi/npm/dvreportermodel}Value"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RankVariationMediator", propOrder = {
    "metrics",
    "numberOfResults",
    "stats",
    "topRank",
    "valueOver",
    "valueUnder"
})
public class RankVariationMediator
    extends Mediator
{

    @XmlElement(required = true)
    protected String metrics;
    protected int numberOfResults;
    @XmlElement(required = true)
    protected String stats;
    protected boolean topRank;
    @XmlElement(required = true)
    protected Value valueOver;
    @XmlElement(required = true)
    protected Value valueUnder;

    /**
     * Gets the value of the metrics property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetrics() {
        return metrics;
    }

    /**
     * Sets the value of the metrics property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetrics(String value) {
        this.metrics = value;
    }

    /**
     * Gets the value of the numberOfResults property.
     * 
     */
    public int getNumberOfResults() {
        return numberOfResults;
    }

    /**
     * Sets the value of the numberOfResults property.
     * 
     */
    public void setNumberOfResults(int value) {
        this.numberOfResults = value;
    }

    /**
     * Gets the value of the stats property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStats() {
        return stats;
    }

    /**
     * Sets the value of the stats property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStats(String value) {
        this.stats = value;
    }

    /**
     * Gets the value of the topRank property.
     * 
     */
    public boolean isTopRank() {
        return topRank;
    }

    /**
     * Sets the value of the topRank property.
     * 
     */
    public void setTopRank(boolean value) {
        this.topRank = value;
    }

    /**
     * Gets the value of the valueOver property.
     * 
     * @return
     *     possible object is
     *     {@link Value }
     *     
     */
    public Value getValueOver() {
        return valueOver;
    }

    /**
     * Sets the value of the valueOver property.
     * 
     * @param value
     *     allowed object is
     *     {@link Value }
     *     
     */
    public void setValueOver(Value value) {
        this.valueOver = value;
    }

    /**
     * Gets the value of the valueUnder property.
     * 
     * @return
     *     possible object is
     *     {@link Value }
     *     
     */
    public Value getValueUnder() {
        return valueUnder;
    }

    /**
     * Sets the value of the valueUnder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Value }
     *     
     */
    public void setValueUnder(Value value) {
        this.valueUnder = value;
    }

}
