//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.06 at 01:17:17 PM IST 
//


package com.ibm.csi.npm.dvreportmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RatioMediator complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RatioMediator">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ibm.com/csi/npm/dvreportermodel}ChartMediator">
 *       &lt;sequence>
 *         &lt;element name="groupRatio" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="metricFromUrl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RatioMediator", propOrder = {
    "groupRatio",
    "metricFromUrl"
})
public class RatioMediator
    extends ChartMediator
{

    protected boolean groupRatio;
    protected String metricFromUrl;

    /**
     * Gets the value of the groupRatio property.
     * 
     */
    public boolean isGroupRatio() {
        return groupRatio;
    }

    /**
     * Sets the value of the groupRatio property.
     * 
     */
    public void setGroupRatio(boolean value) {
        this.groupRatio = value;
    }

    /**
     * Gets the value of the metricFromUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetricFromUrl() {
        return metricFromUrl;
    }

    /**
     * Sets the value of the metricFromUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetricFromUrl(String value) {
        this.metricFromUrl = value;
    }

}
