//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.06 at 01:17:17 PM IST 
//


package com.ibm.csi.npm.dvreportmodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Reporter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Reporter">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="blockHeight" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="bootstrapCols" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="totalrows" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="totalcols" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="localized" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ReportWidget" type="{http://www.ibm.com/csi/npm/dvreportermodel}WidgetConfig" maxOccurs="unbounded"/>
 *         &lt;element name="reportGrpID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Reporter", propOrder = {
    "name",
    "id",
    "blockHeight",
    "bootstrapCols",
    "totalrows",
    "totalcols",
    "localized",
    "reportWidget",
    "reportGrpID"
})
public class Reporter {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String id;
    protected int blockHeight;
    protected int bootstrapCols;
    protected Integer totalrows;
    protected Integer totalcols;
    @XmlElement(defaultValue = "true")
    protected Boolean localized;
    @XmlElement(name = "ReportWidget", required = true)
    protected List<WidgetConfig> reportWidget;
    protected String reportGrpID;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the blockHeight property.
     * 
     */
    public int getBlockHeight() {
        return blockHeight;
    }

    /**
     * Sets the value of the blockHeight property.
     * 
     */
    public void setBlockHeight(int value) {
        this.blockHeight = value;
    }

    /**
     * Gets the value of the bootstrapCols property.
     * 
     */
    public int getBootstrapCols() {
        return bootstrapCols;
    }

    /**
     * Sets the value of the bootstrapCols property.
     * 
     */
    public void setBootstrapCols(int value) {
        this.bootstrapCols = value;
    }

    /**
     * Gets the value of the totalrows property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalrows() {
        return totalrows;
    }

    /**
     * Sets the value of the totalrows property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalrows(Integer value) {
        this.totalrows = value;
    }

    /**
     * Gets the value of the totalcols property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalcols() {
        return totalcols;
    }

    /**
     * Sets the value of the totalcols property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalcols(Integer value) {
        this.totalcols = value;
    }

    /**
     * Gets the value of the localized property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLocalized() {
        return localized;
    }

    /**
     * Sets the value of the localized property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLocalized(Boolean value) {
        this.localized = value;
    }

    /**
     * Gets the value of the reportWidget property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reportWidget property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReportWidget().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WidgetConfig }
     * 
     * 
     */
    public List<WidgetConfig> getReportWidget() {
        if (reportWidget == null) {
            reportWidget = new ArrayList<WidgetConfig>();
        }
        return this.reportWidget;
    }

    /**
     * Gets the value of the reportGrpID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportGrpID() {
        return reportGrpID;
    }

    /**
     * Sets the value of the reportGrpID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportGrpID(String value) {
        this.reportGrpID = value;
    }

}
