//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.06 at 01:17:17 PM IST 
//


package com.ibm.csi.npm.dvreportmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RptTableWidget complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RptTableWidget">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ibm.com/csi/npm/dvreportermodel}TableWidget">
 *       &lt;sequence>
 *         &lt;element name="drilldown" type="{http://www.ibm.com/csi/npm/dvreportermodel}Drilldown"/>
 *         &lt;element name="headings" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="metricDisplayPrevious" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="metricFormat" type="{http://www.ibm.com/csi/npm/dvreportermodel}MeticsFormat"/>
 *         &lt;element name="metricsLabels" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="propertiesLabels" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="resourceLabels" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="statsLabels" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="upgradeConditionLabels" type="{http://www.ibm.com/csi/npm/dvreportermodel}upgradeConditionLabels"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RptTableWidget", propOrder = {
    "drilldown",
    "headings",
    "metricDisplayPrevious",
    "metricFormat",
    "metricsLabels",
    "propertiesLabels",
    "resourceLabels",
    "statsLabels",
    "upgradeConditionLabels"
})
public class RptTableWidget
    extends TableWidget
{

    @XmlElement(required = true)
    protected Drilldown drilldown;
    @XmlElement(required = true)
    protected String headings;
    protected boolean metricDisplayPrevious;
    @XmlElement(required = true)
    protected MeticsFormat metricFormat;
    @XmlElement(required = true)
    protected String metricsLabels;
    @XmlElement(required = true)
    protected String propertiesLabels;
    @XmlElement(required = true)
    protected String resourceLabels;
    @XmlElement(required = true)
    protected String statsLabels;
    @XmlElement(required = true)
    protected UpgradeConditionLabels upgradeConditionLabels;

    /**
     * Gets the value of the drilldown property.
     * 
     * @return
     *     possible object is
     *     {@link Drilldown }
     *     
     */
    public Drilldown getDrilldown() {
        return drilldown;
    }

    /**
     * Sets the value of the drilldown property.
     * 
     * @param value
     *     allowed object is
     *     {@link Drilldown }
     *     
     */
    public void setDrilldown(Drilldown value) {
        this.drilldown = value;
    }

    /**
     * Gets the value of the headings property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeadings() {
        return headings;
    }

    /**
     * Sets the value of the headings property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeadings(String value) {
        this.headings = value;
    }

    /**
     * Gets the value of the metricDisplayPrevious property.
     * 
     */
    public boolean isMetricDisplayPrevious() {
        return metricDisplayPrevious;
    }

    /**
     * Sets the value of the metricDisplayPrevious property.
     * 
     */
    public void setMetricDisplayPrevious(boolean value) {
        this.metricDisplayPrevious = value;
    }

    /**
     * Gets the value of the metricFormat property.
     * 
     * @return
     *     possible object is
     *     {@link MeticsFormat }
     *     
     */
    public MeticsFormat getMetricFormat() {
        return metricFormat;
    }

    /**
     * Sets the value of the metricFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeticsFormat }
     *     
     */
    public void setMetricFormat(MeticsFormat value) {
        this.metricFormat = value;
    }

    /**
     * Gets the value of the metricsLabels property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetricsLabels() {
        return metricsLabels;
    }

    /**
     * Sets the value of the metricsLabels property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetricsLabels(String value) {
        this.metricsLabels = value;
    }

    /**
     * Gets the value of the propertiesLabels property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertiesLabels() {
        return propertiesLabels;
    }

    /**
     * Sets the value of the propertiesLabels property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertiesLabels(String value) {
        this.propertiesLabels = value;
    }

    /**
     * Gets the value of the resourceLabels property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceLabels() {
        return resourceLabels;
    }

    /**
     * Sets the value of the resourceLabels property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceLabels(String value) {
        this.resourceLabels = value;
    }

    /**
     * Gets the value of the statsLabels property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatsLabels() {
        return statsLabels;
    }

    /**
     * Sets the value of the statsLabels property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatsLabels(String value) {
        this.statsLabels = value;
    }

    /**
     * Gets the value of the upgradeConditionLabels property.
     * 
     * @return
     *     possible object is
     *     {@link UpgradeConditionLabels }
     *     
     */
    public UpgradeConditionLabels getUpgradeConditionLabels() {
        return upgradeConditionLabels;
    }

    /**
     * Sets the value of the upgradeConditionLabels property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpgradeConditionLabels }
     *     
     */
    public void setUpgradeConditionLabels(UpgradeConditionLabels value) {
        this.upgradeConditionLabels = value;
    }

}
