//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.06 at 01:17:17 PM IST 
//


package com.ibm.csi.npm.dvreportmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for upgradeConditionLabels complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="upgradeConditionLabels">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="levelLabel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="predictedDateLabel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ruleLabel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="trendDirLabel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "upgradeConditionLabels", propOrder = {
    "label",
    "levelLabel",
    "predictedDateLabel",
    "ruleLabel",
    "trendDirLabel"
})
public class UpgradeConditionLabels {

    @XmlElement(required = true)
    protected String label;
    @XmlElement(required = true)
    protected String levelLabel;
    @XmlElement(required = true)
    protected String predictedDateLabel;
    @XmlElement(required = true)
    protected String ruleLabel;
    @XmlElement(required = true)
    protected String trendDirLabel;

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the levelLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevelLabel() {
        return levelLabel;
    }

    /**
     * Sets the value of the levelLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevelLabel(String value) {
        this.levelLabel = value;
    }

    /**
     * Gets the value of the predictedDateLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPredictedDateLabel() {
        return predictedDateLabel;
    }

    /**
     * Sets the value of the predictedDateLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPredictedDateLabel(String value) {
        this.predictedDateLabel = value;
    }

    /**
     * Gets the value of the ruleLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRuleLabel() {
        return ruleLabel;
    }

    /**
     * Sets the value of the ruleLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRuleLabel(String value) {
        this.ruleLabel = value;
    }

    /**
     * Gets the value of the trendDirLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrendDirLabel() {
        return trendDirLabel;
    }

    /**
     * Sets the value of the trendDirLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrendDirLabel(String value) {
        this.trendDirLabel = value;
    }

}
