//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.06 at 01:17:17 PM IST 
//


package com.ibm.csi.npm.dvreportmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ViolationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ViolationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="baseline" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="burst" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="risk" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="period" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ViolationType", propOrder = {
    "baseline",
    "burst",
    "risk",
    "period"
})
public class ViolationType {

    protected boolean baseline;
    protected boolean burst;
    protected boolean risk;
    protected boolean period;

    /**
     * Gets the value of the baseline property.
     * 
     */
    public boolean isBaseline() {
        return baseline;
    }

    /**
     * Sets the value of the baseline property.
     * 
     */
    public void setBaseline(boolean value) {
        this.baseline = value;
    }

    /**
     * Gets the value of the burst property.
     * 
     */
    public boolean isBurst() {
        return burst;
    }

    /**
     * Sets the value of the burst property.
     * 
     */
    public void setBurst(boolean value) {
        this.burst = value;
    }

    /**
     * Gets the value of the risk property.
     * 
     */
    public boolean isRisk() {
        return risk;
    }

    /**
     * Sets the value of the risk property.
     * 
     */
    public void setRisk(boolean value) {
        this.risk = value;
    }

    /**
     * Gets the value of the period property.
     * 
     */
    public boolean isPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     * 
     */
    public void setPeriod(boolean value) {
        this.period = value;
    }

}
