//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.25 at 11:07:41 PM IST 
//


package com.ibm.csi.npm.dashjson;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for caseList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="caseList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="default" type="{http://www.ibm.com/csi/npm/dashjson}storeDefaultList" minOccurs="0"/>
 *         &lt;element name="timePeriodLastDay" type="{http://www.ibm.com/csi/npm/dashjson}storeDefaultList" minOccurs="0"/>
 *         &lt;element name="timePeriodToday" type="{http://www.ibm.com/csi/npm/dashjson}storeDefaultList" minOccurs="0"/>
 *         &lt;element name="timePeriodLastMonth" type="{http://www.ibm.com/csi/npm/dashjson}storeDefaultList" minOccurs="0"/>
 *         &lt;element name="timePeriodLastWeek" type="{http://www.ibm.com/csi/npm/dashjson}storeDefaultList" minOccurs="0"/>
 *         &lt;element name="timePeriodLastYear" type="{http://www.ibm.com/csi/npm/dashjson}storeDefaultList" minOccurs="0"/>
 *         &lt;element name="timePeriodCustom" type="{http://www.ibm.com/csi/npm/dashjson}storeDefaultList" minOccurs="0"/>
 *         &lt;element name="timeSpancustom" type="{http://www.ibm.com/csi/npm/dashjson}storeDefaultList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "caseList", propOrder = {
    "_default",
    "timePeriodLastDay",
    "timePeriodToday",
    "timePeriodLastMonth",
    "timePeriodLastWeek",
    "timePeriodLastYear",
    "timePeriodCustom",
    "timeSpancustom"
})
public class CaseList {

    @XmlElement(name = "default")
    protected StoreDefaultList _default;
    protected StoreDefaultList timePeriodLastDay;
    protected StoreDefaultList timePeriodToday;
    protected StoreDefaultList timePeriodLastMonth;
    protected StoreDefaultList timePeriodLastWeek;
    protected StoreDefaultList timePeriodLastYear;
    protected StoreDefaultList timePeriodCustom;
    protected StoreDefaultList timeSpancustom;

    /**
     * Gets the value of the default property.
     * 
     * @return
     *     possible object is
     *     {@link StoreDefaultList }
     *     
     */
    public StoreDefaultList getDefault() {
        return _default;
    }

    /**
     * Sets the value of the default property.
     * 
     * @param value
     *     allowed object is
     *     {@link StoreDefaultList }
     *     
     */
    public void setDefault(StoreDefaultList value) {
        this._default = value;
    }

    /**
     * Gets the value of the timePeriodLastDay property.
     * 
     * @return
     *     possible object is
     *     {@link StoreDefaultList }
     *     
     */
    public StoreDefaultList getTimePeriodLastDay() {
        return timePeriodLastDay;
    }

    /**
     * Sets the value of the timePeriodLastDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link StoreDefaultList }
     *     
     */
    public void setTimePeriodLastDay(StoreDefaultList value) {
        this.timePeriodLastDay = value;
    }

    /**
     * Gets the value of the timePeriodToday property.
     * 
     * @return
     *     possible object is
     *     {@link StoreDefaultList }
     *     
     */
    public StoreDefaultList getTimePeriodToday() {
        return timePeriodToday;
    }

    /**
     * Sets the value of the timePeriodToday property.
     * 
     * @param value
     *     allowed object is
     *     {@link StoreDefaultList }
     *     
     */
    public void setTimePeriodToday(StoreDefaultList value) {
        this.timePeriodToday = value;
    }

    /**
     * Gets the value of the timePeriodLastMonth property.
     * 
     * @return
     *     possible object is
     *     {@link StoreDefaultList }
     *     
     */
    public StoreDefaultList getTimePeriodLastMonth() {
        return timePeriodLastMonth;
    }

    /**
     * Sets the value of the timePeriodLastMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link StoreDefaultList }
     *     
     */
    public void setTimePeriodLastMonth(StoreDefaultList value) {
        this.timePeriodLastMonth = value;
    }

    /**
     * Gets the value of the timePeriodLastWeek property.
     * 
     * @return
     *     possible object is
     *     {@link StoreDefaultList }
     *     
     */
    public StoreDefaultList getTimePeriodLastWeek() {
        return timePeriodLastWeek;
    }

    /**
     * Sets the value of the timePeriodLastWeek property.
     * 
     * @param value
     *     allowed object is
     *     {@link StoreDefaultList }
     *     
     */
    public void setTimePeriodLastWeek(StoreDefaultList value) {
        this.timePeriodLastWeek = value;
    }

    /**
     * Gets the value of the timePeriodLastYear property.
     * 
     * @return
     *     possible object is
     *     {@link StoreDefaultList }
     *     
     */
    public StoreDefaultList getTimePeriodLastYear() {
        return timePeriodLastYear;
    }

    /**
     * Sets the value of the timePeriodLastYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link StoreDefaultList }
     *     
     */
    public void setTimePeriodLastYear(StoreDefaultList value) {
        this.timePeriodLastYear = value;
    }

    /**
     * Gets the value of the timePeriodCustom property.
     * 
     * @return
     *     possible object is
     *     {@link StoreDefaultList }
     *     
     */
    public StoreDefaultList getTimePeriodCustom() {
        return timePeriodCustom;
    }

    /**
     * Sets the value of the timePeriodCustom property.
     * 
     * @param value
     *     allowed object is
     *     {@link StoreDefaultList }
     *     
     */
    public void setTimePeriodCustom(StoreDefaultList value) {
        this.timePeriodCustom = value;
    }

    /**
     * Gets the value of the timeSpancustom property.
     * 
     * @return
     *     possible object is
     *     {@link StoreDefaultList }
     *     
     */
    public StoreDefaultList getTimeSpancustom() {
        return timeSpancustom;
    }

    /**
     * Sets the value of the timeSpancustom property.
     * 
     * @param value
     *     allowed object is
     *     {@link StoreDefaultList }
     *     
     */
    public void setTimeSpancustom(StoreDefaultList value) {
        this.timeSpancustom = value;
    }

}
