//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.25 at 11:07:41 PM IST 
//


package com.ibm.csi.npm.dashjson;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for chartIdentityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="chartIdentityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="class" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="drilldowntype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parameter" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="master" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tooltipText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tabTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="extracolumns" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="extraparameters" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="extraparams" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="targetDashboard" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="targetDashboards" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "chartIdentityType", propOrder = {
    "name",
    "clazz",
    "drilldowntype",
    "type",
    "parameter",
    "master",
    "tooltipText",
    "tabTitle",
    "extracolumns",
    "extraparameters",
    "extraparams",
    "targetDashboard",
    "targetDashboards"
})
public class ChartIdentityType {

    protected String name;
    @XmlElement(name = "class")
    protected String clazz;
    @XmlElement(required = true, defaultValue = "navigation")
    protected String drilldowntype;
    @XmlElement(required = true)
    protected String type;
    @XmlElement(required = true)
    protected String parameter;
    protected String master;
    protected String tooltipText;
    protected String tabTitle;
    protected String extracolumns;
    protected String extraparameters;
    protected String extraparams;
    protected String targetDashboard;
    protected String targetDashboards;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the drilldowntype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrilldowntype() {
        return drilldowntype;
    }

    /**
     * Sets the value of the drilldowntype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrilldowntype(String value) {
        this.drilldowntype = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the parameter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParameter() {
        return parameter;
    }

    /**
     * Sets the value of the parameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParameter(String value) {
        this.parameter = value;
    }

    /**
     * Gets the value of the master property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaster() {
        return master;
    }

    /**
     * Sets the value of the master property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaster(String value) {
        this.master = value;
    }

    /**
     * Gets the value of the tooltipText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTooltipText() {
        return tooltipText;
    }

    /**
     * Sets the value of the tooltipText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTooltipText(String value) {
        this.tooltipText = value;
    }

    /**
     * Gets the value of the tabTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTabTitle() {
        return tabTitle;
    }

    /**
     * Sets the value of the tabTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTabTitle(String value) {
        this.tabTitle = value;
    }

    /**
     * Gets the value of the extracolumns property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtracolumns() {
        return extracolumns;
    }

    /**
     * Sets the value of the extracolumns property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtracolumns(String value) {
        this.extracolumns = value;
    }

    /**
     * Gets the value of the extraparameters property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtraparameters() {
        return extraparameters;
    }

    /**
     * Sets the value of the extraparameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtraparameters(String value) {
        this.extraparameters = value;
    }

    /**
     * Gets the value of the extraparams property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtraparams() {
        return extraparams;
    }

    /**
     * Sets the value of the extraparams property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtraparams(String value) {
        this.extraparams = value;
    }

    /**
     * Gets the value of the targetDashboard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetDashboard() {
        return targetDashboard;
    }

    /**
     * Sets the value of the targetDashboard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetDashboard(String value) {
        this.targetDashboard = value;
    }

    /**
     * Gets the value of the targetDashboards property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetDashboards() {
        return targetDashboards;
    }

    /**
     * Sets the value of the targetDashboards property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetDashboards(String value) {
        this.targetDashboards = value;
    }

}
