//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.25 at 11:07:41 PM IST 
//


package com.ibm.csi.npm.dashjson;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for propertiesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="propertiesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="primaryKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dataStore" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="store" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="colors" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ranges" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="labelFontSize" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fontsize" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="axisWidth" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="radius" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="valueAttr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="minimum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="maximum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "propertiesType", propOrder = {
    "title",
    "primaryKey",
    "dataStore",
    "store",
    "colors",
    "ranges",
    "labelFontSize",
    "fontsize",
    "axisWidth",
    "radius",
    "valueAttr",
    "minimum",
    "maximum"
})
public class PropertiesType {

    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected String primaryKey;
    @XmlElement(required = true)
    protected String dataStore;
    @XmlElement(required = true)
    protected String store;
    @XmlElement(required = true)
    protected String colors;
    @XmlElement(required = true)
    protected String ranges;
    @XmlElement(required = true)
    protected String labelFontSize;
    @XmlElement(required = true)
    protected String fontsize;
    @XmlElement(required = true)
    protected String axisWidth;
    @XmlElement(required = true)
    protected String radius;
    @XmlElement(required = true)
    protected String valueAttr;
    @XmlElement(required = true)
    protected String minimum;
    @XmlElement(required = true)
    protected String maximum;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the primaryKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryKey() {
        return primaryKey;
    }

    /**
     * Sets the value of the primaryKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryKey(String value) {
        this.primaryKey = value;
    }

    /**
     * Gets the value of the dataStore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataStore() {
        return dataStore;
    }

    /**
     * Sets the value of the dataStore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataStore(String value) {
        this.dataStore = value;
    }

    /**
     * Gets the value of the store property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStore() {
        return store;
    }

    /**
     * Sets the value of the store property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStore(String value) {
        this.store = value;
    }

    /**
     * Gets the value of the colors property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColors() {
        return colors;
    }

    /**
     * Sets the value of the colors property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColors(String value) {
        this.colors = value;
    }

    /**
     * Gets the value of the ranges property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRanges() {
        return ranges;
    }

    /**
     * Sets the value of the ranges property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRanges(String value) {
        this.ranges = value;
    }

    /**
     * Gets the value of the labelFontSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabelFontSize() {
        return labelFontSize;
    }

    /**
     * Sets the value of the labelFontSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabelFontSize(String value) {
        this.labelFontSize = value;
    }

    /**
     * Gets the value of the fontsize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFontsize() {
        return fontsize;
    }

    /**
     * Sets the value of the fontsize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFontsize(String value) {
        this.fontsize = value;
    }

    /**
     * Gets the value of the axisWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAxisWidth() {
        return axisWidth;
    }

    /**
     * Sets the value of the axisWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAxisWidth(String value) {
        this.axisWidth = value;
    }

    /**
     * Gets the value of the radius property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRadius() {
        return radius;
    }

    /**
     * Sets the value of the radius property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRadius(String value) {
        this.radius = value;
    }

    /**
     * Gets the value of the valueAttr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueAttr() {
        return valueAttr;
    }

    /**
     * Sets the value of the valueAttr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueAttr(String value) {
        this.valueAttr = value;
    }

    /**
     * Gets the value of the minimum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinimum() {
        return minimum;
    }

    /**
     * Sets the value of the minimum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinimum(String value) {
        this.minimum = value;
    }

    /**
     * Gets the value of the maximum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaximum() {
        return maximum;
    }

    /**
     * Sets the value of the maximum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaximum(String value) {
        this.maximum = value;
    }

}
