//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.25 at 11:07:41 PM IST 
//


package com.ibm.csi.npm.dashjson;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for toolbarSeriesList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="toolbarSeriesList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="inbound" type="{http://www.ibm.com/csi/npm/dashjson}inboundSeriesList" maxOccurs="unbounded"/>
 *         &lt;element name="outbound" type="{http://www.ibm.com/csi/npm/dashjson}outboundSeriesList" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "toolbarSeriesList", propOrder = {
    "inbound",
    "outbound"
})
public class ToolbarSeriesList {

    @XmlElement(required = true)
    protected List<InboundSeriesList> inbound;
    @XmlElement(required = true)
    protected List<OutboundSeriesList> outbound;

    /**
     * Gets the value of the inbound property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inbound property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInbound().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InboundSeriesList }
     * 
     * 
     */
    public List<InboundSeriesList> getInbound() {
        if (inbound == null) {
            inbound = new ArrayList<InboundSeriesList>();
        }
        return this.inbound;
    }

    /**
     * Gets the value of the outbound property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the outbound property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutbound().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OutboundSeriesList }
     * 
     * 
     */
    public List<OutboundSeriesList> getOutbound() {
        if (outbound == null) {
            outbound = new ArrayList<OutboundSeriesList>();
        }
        return this.outbound;
    }

}
