//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.24 at 04:56:15 PM IST 
//


package com.ibm.csi.npm.dvreportinput;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WidgetConfigInput complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WidgetConfigInput">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="widget" type="{com.ibm.csi.npm.dvreportinput}WidgetInput"/>
 *         &lt;element name="mediator" type="{com.ibm.csi.npm.dvreportinput}MediatorInput"/>
 *         &lt;element name="title" type="{com.ibm.csi.npm.dvreportinput}TitleInput"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WidgetConfigInput", propOrder = {
    "widget",
    "mediator",
    "title"
})
public class WidgetConfigInput {

    @XmlElement(required = true)
    protected WidgetInput widget;
    @XmlElement(required = true)
    protected MediatorInput mediator;
    @XmlElement(required = true)
    protected TitleInput title;

    /**
     * Gets the value of the widget property.
     * 
     * @return
     *     possible object is
     *     {@link WidgetInput }
     *     
     */
    public WidgetInput getWidget() {
        return widget;
    }

    /**
     * Sets the value of the widget property.
     * 
     * @param value
     *     allowed object is
     *     {@link WidgetInput }
     *     
     */
    public void setWidget(WidgetInput value) {
        this.widget = value;
    }

    /**
     * Gets the value of the mediator property.
     * 
     * @return
     *     possible object is
     *     {@link MediatorInput }
     *     
     */
    public MediatorInput getMediator() {
        return mediator;
    }

    /**
     * Sets the value of the mediator property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediatorInput }
     *     
     */
    public void setMediator(MediatorInput value) {
        this.mediator = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link TitleInput }
     *     
     */
    public TitleInput getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link TitleInput }
     *     
     */
    public void setTitle(TitleInput value) {
        this.title = value;
    }

}
