//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.24 at 04:56:15 PM IST 
//


package com.ibm.csi.npm.dvreportinput;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ibm.csi.npm.dvreportinput package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ReporterInput_QNAME = new QName("com.ibm.csi.npm.dvreportinput", "reporterInput");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ibm.csi.npm.dvreportinput
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReporterInput }
     * 
     */
    public ReporterInput createReporterInput() {
        return new ReporterInput();
    }

    /**
     * Create an instance of {@link WidgetConfigInput }
     * 
     */
    public WidgetConfigInput createWidgetConfigInput() {
        return new WidgetConfigInput();
    }

    /**
     * Create an instance of {@link TitleInput }
     * 
     */
    public TitleInput createTitleInput() {
        return new TitleInput();
    }

    /**
     * Create an instance of {@link WidgetInput }
     * 
     */
    public WidgetInput createWidgetInput() {
        return new WidgetInput();
    }

    /**
     * Create an instance of {@link MediatorInput }
     * 
     */
    public MediatorInput createMediatorInput() {
        return new MediatorInput();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReporterInput }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "com.ibm.csi.npm.dvreportinput", name = "reporterInput")
    public JAXBElement<ReporterInput> createReporterInput(ReporterInput value) {
        return new JAXBElement<ReporterInput>(_ReporterInput_QNAME, ReporterInput.class, null, value);
    }

}
