//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.24 at 04:56:15 PM IST 
//


package com.ibm.csi.npm.dvreportinput;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReporterInput complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReporterInput">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="reporterId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="widgetConfigInput" type="{com.ibm.csi.npm.dvreportinput}WidgetConfigInput" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement
@XmlType(name = "ReporterInput", propOrder = {
    "reporterId",
    "widgetConfigInput"
})
public class ReporterInput {

    protected int reporterId;
    @XmlElement(required = true)
    protected List<WidgetConfigInput> widgetConfigInput;

    /**
     * Gets the value of the reporterId property.
     * 
     */
    public int getReporterId() {
        return reporterId;
    }

    /**
     * Sets the value of the reporterId property.
     * 
     */
    public void setReporterId(int value) {
        this.reporterId = value;
    }

    /**
     * Gets the value of the widgetConfigInput property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the widgetConfigInput property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWidgetConfigInput().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WidgetConfigInput }
     * 
     * 
     */
    public List<WidgetConfigInput> getWidgetConfigInput() {
        if (widgetConfigInput == null) {
            widgetConfigInput = new ArrayList<WidgetConfigInput>();
        }
        return this.widgetConfigInput;
    }

}
